import numpy as np
import pandas as pd
from gymnasium import spaces
from typing import Optional, Tuple
from custom_envs.base_trading_env import BaseTradingEnv

class TradingEnvV5(BaseTradingEnv):
    """Trading environment for Phase 1.3 (Production-ready futures).
    
    Key Features:
    - Initialized with pd.DataFrame (allows dynamic column access)
    - Dynamic Slippage based on Garman-Klass Volatility
    - Funding Rate mechanics (longs pay shorts)
    - Asymmetric Sortino-style step reward (penalizes downside)
    - Hardcoded Risk Management (-10% Max Drawdown -> Margin Call)
    """

    ACTIONS = {0: "HOLD", 1: "BUY", 2: "SELL"}
    SIZE_LEVELS = [i / 10 for i in range(1, 11)]

    def __init__(
        self,
        df: pd.DataFrame,
        initial_deposit: float = 100_000.0,
        commission: float = 0.0005,
        leverage: float = 1.0,
        base_slippage: float = 0.0001,  # 1 bps base slippage
        volatility_factor: float = 0.05, # Multiplier for gk_volatility
        downside_penalty: float = 3.0,   # Sortino proxy: penalize losses 3x more
        max_drawdown_pct: float = 0.10,  # 10% max DD -> termination
        continuous_action: bool = True,  # True for PPO/SAC, False for DQN
        t_max: int = 1440,
        invalid_action_penalty: float = -0.00005,
        domain_randomization: bool = True,
    ):
        super().__init__(initial_deposit=initial_deposit, commission=commission, leverage=leverage)
        
        self.df = df.reset_index(drop=True)
        self.continuous_action = continuous_action
        self.domain_randomization = domain_randomization
        
        # Интеграция с FeatureGenerator: читаем готовый вектор
        if 'state_vector' not in self.df.columns:
            raise ValueError("DataFrame must contain 'state_vector' column generated by FeatureGenerator")
        
        self.features = np.stack(self.df['state_vector'].values).astype(np.float32)
        
        if 'close' not in self.df.columns:
            raise ValueError("DataFrame must contain 'close' column")
            
        self.base_slippage = base_slippage
        self.volatility_factor = volatility_factor
        self.downside_penalty = downside_penalty
        self.max_drawdown_pct = max_drawdown_pct
        self.t_max = t_max
        self.invalid_action_penalty = invalid_action_penalty
        
        self.orig_base_slippage = base_slippage
        self.orig_commission = commission
        self.orig_downside_penalty = downside_penalty

        self.num_features = self.features.shape[1]
        
        if self.continuous_action:
            # PPO/SAC: Action is a single float [-1.0, 1.0] representing target position
            self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(1,), dtype=np.float32)
        else:
            # DQN: Discrete actions [Hold/Buy/Sell, Size Level]
            self.action_space = spaces.MultiDiscrete([3, 10])

        obs_dim = self.num_features + 10
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(obs_dim,), dtype=np.float32
        )

        self.current_step = 0
        self.start_index = 0
        self.reset()

    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)
        if seed is not None:
            np.random.seed(seed)
            
        if self.domain_randomization:
            self.commission = np.random.uniform(0.0003, 0.001)
            self.base_slippage = np.random.uniform(0.00005, 0.0003)
            self.downside_penalty = np.random.uniform(2.0, 5.0)
        else:
            self.commission = self.orig_commission
            self.base_slippage = self.orig_base_slippage
            self.downside_penalty = self.orig_downside_penalty

        if len(self.features) <= self.t_max:
            self.start_index = 0
            self.t_max = len(self.features) - 1
        else:
            self.start_index = np.random.randint(0, len(self.features) - self.t_max)

        self.current_step = self.start_index
        self._reset_portfolio()
        
        self.prev_portfolio_value = self.initial_deposit
        self.max_portfolio_value = self.initial_deposit

        return self._get_observation(), {}

    def get_possible_actions(self) -> list[list]:
        actions = [[0, 0]]
        if self.continuous_action:
            return actions  # Not used in continuous mode
            
        if self._can_trade():
            for size_idx in range(10):
                actions.append([1, size_idx])
                actions.append([2, size_idx])
        else:
            if self.positions_long:
                for size_idx in range(10):
                    actions.append([2, size_idx])
            if self.positions_short:
                for size_idx in range(10):
                    actions.append([1, size_idx])
        return actions

    def _get_current_price(self) -> float:
        return self.df['close'].iloc[self.current_step]

    def step(self, action: np.ndarray) -> Tuple:
        if self.continuous_action:
            action_val = np.clip(float(action[0]), -1.0, 1.0)
            size_fraction = abs(action_val)
            if action_val > 0.05:
                action_type = 1 # BUY
            elif action_val < -0.05:
                action_type = 2 # SELL
            else:
                action_type = 0 # HOLD
                size_fraction = 0.0
        else:
            action_type = int(action[0])
            size_level = int(action[1])
            size_fraction = self.SIZE_LEVELS[size_level]

        executed = False
        mid_price = self._get_current_price()
        
        # 1. Calculate Slippage
        gk_vol = self.df['gk_volatility'].iloc[self.current_step] if 'gk_volatility' in self.df.columns else 0.0
        slippage = self.base_slippage + self.volatility_factor * gk_vol
        buy_price = mid_price * (1 + slippage)
        sell_price = mid_price * (1 - slippage)

        # 2. Execute Action
        if action_type == 1 and size_fraction > 0:
            executed = self._execute_buy(size_fraction, buy_price)
        elif action_type == 2 and size_fraction > 0:
            executed = self._execute_sell(size_fraction, sell_price)

        attempted_trade = (action_type in [1, 2]) and (size_fraction > 0)
        
        # 3. Apply Funding Fees
        if 'fundingRate' in self.df.columns:
            funding_rate = self.df['fundingRate'].iloc[self.current_step]
            long_volume = sum(v for _, v in self.positions_long)
            short_volume = sum(v for _, v in self.positions_short)
            net_position_value = (long_volume - short_volume) * mid_price
            funding_fee = funding_rate * net_position_value
            self.deposit -= funding_fee # If net_position_value > 0 (long), we pay funding_rate.

        self.current_step += 1
        
        # 4. Calculate Portfolio Value & Drawdown
        new_mid_price = self._get_current_price() if self.current_step < len(self.df) else mid_price
        current_portfolio_value = self.get_portfolio_value(new_mid_price)
        
        self.max_portfolio_value = max(self.max_portfolio_value, current_portfolio_value)
        drawdown = (current_portfolio_value - self.max_portfolio_value) / self.max_portfolio_value
        
        # 5. Reward Calculation (Sortino Proxy)
        step_return = (current_portfolio_value - self.prev_portfolio_value) / self.prev_portfolio_value
        
        if step_return > 0:
            reward = step_return
        else:
            reward = step_return * self.downside_penalty
            
        self.prev_portfolio_value = current_portfolio_value
        
        # Risk penalty for huge positions
        if executed and size_fraction > 0.5:
            reward += -0.001 * ((size_fraction - 0.5) / 0.5)
            
        if attempted_trade and not executed:
            reward += self.invalid_action_penalty
            
        # 6. Check Done & Margin Call
        done = False
        margin_call = False
        if drawdown <= -self.max_drawdown_pct:
            done = True
            margin_call = True
            reward -= 0.1 # Huge penalty for margin call
        elif self.current_step - self.start_index >= self.t_max:
            done = True
        elif self.deposit <= 0.01 and not self.positions_long and not self.positions_short:
            done = True
            
        if done:
            self._finalize_pnl()

        info = {
            "pnl": (current_portfolio_value - self.initial_deposit) / self.initial_deposit * 100,
            "deposit": self.deposit,
            "long_positions": len(self.positions_long),
            "short_positions": len(self.positions_short),
            "executed": executed,
            "margin_call": margin_call,
            "drawdown": drawdown * 100,
            "real_reward": reward
        }

        return self._get_observation(), reward, done, False, info

    def _finalize_pnl(self):
        price = self._get_current_price()
        if self.positions_long:
            self._close_long(sum(v for _, v in self.positions_long), price)
        if self.positions_short:
            self._close_short(sum(v for _, v in self.positions_short), price)

    def _get_observation(self) -> np.ndarray:
        features = self.features[self.current_step]
        price = self._get_current_price()
        deposit_norm = self.deposit / self.initial_deposit
        
        long_volume = sum(v for _, v in self.positions_long)
        long_volume_norm = long_volume * price / (self.initial_deposit * self.leverage)
        long_avg_ratio = (self.avg_price_long / price - 1.0) if self.avg_price_long > 0 else 0.0

        short_volume = sum(v for _, v in self.positions_short)
        short_volume_norm = short_volume * price / (self.initial_deposit * self.leverage)
        short_avg_ratio = (self.avg_price_short / price - 1.0) if self.avg_price_short > 0 else 0.0

        unrealized_pnl = self._unrealized_pnl_total(price)
        can_trade = float(self._can_trade())

        return np.concatenate([
            features,
            [
                deposit_norm,
                long_volume_norm,
                long_avg_ratio,
                short_volume_norm,
                short_avg_ratio,
                unrealized_pnl,
                can_trade,
                self.leverage - 1.0,
                0.0,
                0.0,
            ]
        ]).astype(np.float32)

if __name__ == "__main__":
    import pandas as pd
    
    # Mock data
    size = 1000
    df = pd.DataFrame({
        'close': 50000 + np.random.randn(size).cumsum() * 10,
        'gk_volatility': np.random.uniform(0.001, 0.01, size),
        'fundingRate': np.random.uniform(-0.0001, 0.0001, size)
    })
    
    features = np.random.randn(size, 15).astype(np.float32)
    feature_cols = [f'feat_{i}' for i in range(15)]
    for i, col in enumerate(feature_cols):
        df[col] = features[:, i]
        
    env = TradingEnvV5(df=df, feature_cols=feature_cols, t_max=500)
    obs, _ = env.reset()
    
    for i in range(20):
        action = env.action_space.sample()
        obs, reward, done, _, info = env.step(action)
        if done: break
